module.exports = {
    "IDE - Develorper PC":["Visual Studio Code","Eclipse","Netbeans","IntelliJ","Android Studio"],
    "Web Frameworks":["GWT","Spring MVC","Struts","Spring Boot","Vaadin","JSF","OracleJet","Express.js"],
    "Mobile framework":["OracleJet","Android Studio","Cordova"],
    "Non JVM Languages":["Python","PHP","C#","Node.js"],
    "Java SE":["Java 6","Java 7","Java 8","Java 9","Java 10"],
    "Java EE":["Java EE 6","Java EE 7","Java EE 8"],
    "Tool to communicate":["Slack","Hangouts","Email"],
    "MQ":["Apache Pulsar","Apache bookkeeper"],
    "Log Management":["Splunk"],
    "Alert and Visualization":["Grafana","Nagios"],
    "Block Chain":["Etherum","BlockChain","MultiChain","Hyperledger"],
    "Microservices":["REST","GraphQL"],
    "Developer / Testing":["Chef","Ansible"],
    "ECommerce":["uCommerce","Magento"],
    "Database":["MySQL","DB2","SQL Server","PostgreSQL","Oracle","MariaDB","MongoDB","Firebase"],
    "ORM":["Hibernate","Spring JDBC","Ecipse Link"],
    "DataWarehouse":["BigData","BI","Data Mining","Streams"],
    "Web Server":["Apache","Nginx"],
    "App Server":["Tomcat","GlassFish","Payara","Jetty","Jboss / WildFly"],
    "Cloud":["Private","Amazon AWS","Azure","Google"],
    "Search Engine":["Solr","Elastic Search"],
    "Monitoring":["Nagios","Kamon"],
    "Cognitive Services":["Translation","Natural lenguaje","ChatBots","Facial recognition","Machine learning","IA"],
    "Containers":["Docker","Lxc","Orchestration","Registry","Compose","Swarm","Jenkins","Containers GUI","HyperContainer","Developer","Logs","Workflow","Optimize"],
    "Cloud approaches":["Serverless","VMs","Containers"],
    "Authentication":["OAuth","Basic","Token"],
    "Control de Versiones":["Git","Subversion","CVS"],
    "Control de Dependencias":["Maven","Gradle","Npm","",""],
    "RPG":["RPG III","Free","CGI","Excel"],
};
